export const DEFAULT_MIRAKL_SUB_TYPE = 'mirakl';

export interface MiraklSubtypeChoice {
  value: string;
  label: string;
}

export const MIRAKL_SUB_TYPE_CHOICES: MiraklSubtypeChoice[] = [
  { value: DEFAULT_MIRAKL_SUB_TYPE, label: 'Mirakl' },
  { value: '1_800_flowers', label: '1-800-Flowers' },
  { value: 'abb', label: 'ABB' },
  { value: 'abbott', label: 'Abbott' },
  { value: 'accor', label: 'Accor' },
  { value: 'acer', label: 'Acer' },
  { value: 'adani', label: 'Adani' },
  { value: 'aena', label: 'AENA' },
  { value: 'afound', label: 'Afound' },
  { value: 'agora', label: 'Agora' },
  { value: 'ahlens', label: 'Ahlens' },
  { value: 'ahold_delhaize', label: 'Ahold Delhaize' },
  { value: 'airbus', label: 'Airbus' },
  { value: 'aksal_group', label: 'Aksal Group' },
  { value: 'al_futtaim', label: 'Al-Futtaim' },
  { value: 'albertsons', label: 'Albertsons' },
  { value: 'alltricks', label: 'Alltricks' },
  { value: 'alshaya', label: 'Alshaya' },
  { value: 'altitude_sports', label: 'Altitude Sports' },
  { value: 'amerisource_bergen', label: 'Amerisource Bergen' },
  { value: 'aniel', label: 'Aniel' },
  { value: 'anjana_investments', label: 'Anjana Investments' },
  { value: 'anthropologie', label: 'Anthropologie' },
  { value: 'anwb', label: 'ANWB' },
  { value: 'arezzo_and_co', label: 'Arezzo&Co' },
  { value: 'asos', label: 'ASOS' },
  { value: 'atlas_for_men', label: 'Atlas For Men' },
  { value: 'auchan', label: 'Auchan' },
  { value: 'aurgi', label: 'Aurgi' },
  { value: 'autodoc', label: 'Autodoc' },
  { value: 'b_and_q', label: 'B&Q' },
  { value: 'baloise', label: 'Baloise' },
  { value: 'bank_of_cyprus', label: 'Bank of Cyprus' },
  { value: 'baur', label: 'Baur' },
  { value: 'bed_bath_and_beyond', label: 'Bed Bath & Beyond' },
  { value: 'beerwulf', label: 'Beerwulf' },
  { value: 'belk', label: 'Belk' },
  { value: 'best_buy', label: 'Best Buy' },
  { value: 'best_secret', label: 'Best Secret' },
  { value: 'bestseller', label: 'Bestseller' },
  { value: 'beter_bed', label: 'Beter Bed' },
  { value: 'bhv', label: 'BHV' },
  { value: 'bigbang', label: 'Bigbang' },
  { value: 'bild_shop', label: 'Bild Shop' },
  { value: 'black_red_white', label: 'Black Red White' },
  { value: 'blokker', label: 'Blokker' },
  { value: 'bloomingdale_s', label: "Bloomingdale's" },
  { value: 'blue_diamond_growers', label: 'Blue Diamond Growers' },
  { value: 'bob_s_discount', label: "Bob's Discount" },
  { value: 'boelter_food_service_exchange', label: 'Boelter - Food Service Exchange' },
  { value: 'bol_com', label: 'Bol.com' },
  { value: 'boohoo', label: 'Boohoo' },
  { value: 'boozt', label: 'Boozt' },
  { value: 'boots', label: 'Boots' },
  { value: 'boticario', label: 'Boticario' },
  { value: 'boulanger', label: 'Boulanger' },
  { value: 'brakes', label: 'Brakes' },
  { value: 'brandalley', label: 'Brandalley' },
  { value: 'brico', label: 'Brico' },
  { value: 'brico_cash', label: 'Brico Cash' },
  { value: 'bricocenter', label: 'Bricocenter' },
  { value: 'brico_depot', label: 'Brico Depot' },
  { value: 'bricomarche', label: 'Bricomarche' },
  { value: 'bulevip', label: 'Bulevip' },
  { value: 'bunnings', label: 'Bunnings' },
  { value: 'business_france', label: 'Business France' },
  { value: 'but', label: 'BUT' },
  { value: 'butlers', label: 'Butlers' },
  { value: 'c_and_a', label: 'C&A' },
  { value: 'c10', label: 'C10' },
  { value: 'cabinets_com', label: 'Cabinets.com' },
  { value: 'camif', label: 'Camif' },
  { value: 'camper', label: 'Camper' },
  { value: 'campings_com', label: 'Campings.com' },
  { value: 'carpetright', label: 'Carpetright' },
  { value: 'carethy', label: 'Carethy' },
  { value: 'carrefour', label: 'Carrefour' },
  { value: 'casa_del_libro', label: 'Casa del Libro' },
  { value: 'casino', label: 'Casino' },
  { value: 'castorama', label: 'Castorama' },
  { value: 'catch', label: 'Catch' },
  { value: 'cdiscount', label: 'Cdiscount' },
  { value: 'central_group_thailand', label: 'Central Group Thailand' },
  { value: 'changi_airport', label: 'Changi Airport' },
  { value: 'chemetall', label: 'Chemetall' },
  { value: 'cheney_brothers', label: 'Cheney Brothers' },
  { value: 'chr_avenue', label: 'CHR Avenue' },
  { value: 'chronopost_pour_de_bon', label: 'Chronopost - Pour De Bon' },
  { value: 'clarel', label: 'Clarel' },
  { value: 'click_frenzy', label: 'Click Frenzy' },
  { value: 'cleor', label: 'Cleor' },
  { value: 'clube_fashion', label: 'Clube Fashion' },
  { value: 'cma_cgm', label: 'CMA CGM' },
  { value: 'coca_cola_europacific_partners', label: 'Coca-Cola Europacific Partners' },
  { value: 'cobasi', label: 'Cobasi' },
  { value: 'coin', label: 'Coin' },
  { value: 'coles', label: 'Coles' },
  { value: 'colombo', label: 'Colombo' },
  { value: 'colruyt', label: 'Colruyt' },
  { value: 'comptoir_sante', label: 'Comptoir Sante' },
  { value: 'conforama', label: 'Conforama' },
  { value: 'conrad', label: 'Conrad' },
  { value: 'continente', label: 'Continente' },
  { value: 'coperama', label: 'Coperama' },
  { value: 'coppel', label: 'Coppel' },
  { value: 'cora', label: 'Cora' },
  { value: 'creavea', label: 'Creavea' },
  { value: 'cultura', label: 'Cultura' },
  { value: 'currys', label: 'Currys' },
  { value: 'dafiti', label: 'Dafiti' },
  { value: 'de_bijenkorf', label: 'De Bijenkorf' },
  { value: 'debenhams', label: 'Debenhams' },
  { value: 'decathlon', label: 'Decathlon' },
  { value: 'delhaize', label: 'Delhaize' },
  { value: 'dia_styling', label: 'Dia Styling' },
  { value: 'disposable_discounter_didi', label: 'Disposable Discounter (DiDi)' },
  { value: 'distriartisan', label: 'Distriartisan' },
  { value: 'do_it_best', label: 'Do it Best' },
  { value: 'doctipharma', label: 'DoctiPharma' },
  { value: 'doto', label: 'Doto' },
  { value: 'dotz', label: 'Dotz' },
  { value: 'douglas', label: 'Douglas' },
  { value: 'dr_max', label: 'Dr. Max' },
  { value: 'dpg_media_group', label: 'DPG Media Group' },
  { value: 'driven_brands', label: 'Driven Brands' },
  { value: 'dubaistore', label: 'DubaiStore' },
  { value: 'eiffage', label: 'Eiffage' },
  { value: 'e_leclerc', label: 'E.Leclerc' },
  { value: 'el_corte_ingles', label: 'El Corte Ingles' },
  { value: 'elkjop', label: 'Elkjop' },
  { value: 'ellos', label: 'Ellos' },
  { value: 'electra', label: 'Electra' },
  { value: 'empik', label: 'Empik' },
  { value: 'engie', label: 'Engie' },
  { value: 'eprice', label: 'ePRICE' },
  { value: 'espace_aubade', label: 'Espace Aubade' },
  { value: 'euronics', label: 'Euronics' },
  { value: 'exito', label: 'Exito' },
  { value: 'exelon', label: 'Exelon' },
  { value: 'expert', label: 'Expert' },
  { value: 'falabella', label: 'Falabella' },
  { value: 'fanatics', label: 'Fanatics' },
  { value: 'farmacias_direct', label: 'Farmacias Direct' },
  { value: 'feelunique', label: 'Feelunique' },
  { value: 'ferguson', label: 'Ferguson' },
  { value: 'fnac_darty', label: 'Fnac Darty' },
  { value: 'fonq', label: 'FonQ' },
  { value: 'fossil', label: 'Fossil' },
  { value: 'france_boissons', label: 'France Boissons' },
  { value: 'freedom_furniture', label: 'Freedom Furniture' },
  { value: 'free_people', label: 'Free People' },
  { value: 'fressnapf_tiernahrungs', label: 'Fressnapf Tiernahrungs' },
  { value: 'fruugo', label: 'Fruugo' },
  { value: 'gacd', label: 'GACD' },
  { value: 'galeries_lafayette', label: 'Galeries Lafayette' },
  { value: 'galeria_karstadt_kaufhof', label: 'Galeria Karstadt Kaufhof' },
  { value: 'game', label: 'Game' },
  { value: 'giant_eagle', label: 'Giant Eagle' },
  { value: 'gifi', label: 'Gifi' },
  { value: 'go_sport', label: 'Go Sport' },
  { value: 'grainger', label: 'Grainger' },
  { value: 'greenweez', label: 'Greenweez' },
  { value: 'grenier_alpin', label: 'Grenier Alpin' },
  { value: 'grupo_andres', label: 'Grupo Andres' },
  { value: 'grupo_distelsa', label: 'Grupo Distelsa' },
  { value: 'grupo_exito', label: 'Grupo Exito' },
  { value: 'h_and_m', label: 'H&M' },
  { value: 'hagebau', label: 'Hagebau' },
  { value: 'halfords', label: 'Halfords' },
  { value: 'happy_size_popken_fashion', label: 'Happy Size - Popken Fashion' },
  { value: 'happytal', label: 'Happytal' },
  { value: 'harvey_nichols', label: 'Harvey Nichols' },
  { value: 'hema', label: 'HEMA' },
  { value: 'hewlett_packard_enterprise', label: 'Hewlett Packard Enterprise' },
  { value: 'home_and_you', label: 'Home & You' },
  { value: 'home24', label: 'Home24' },
  { value: 'homebase', label: 'Homebase' },
  { value: 'home_depot', label: 'Home Depot' },
  { value: 'hornbach', label: 'Hornbach' },
  { value: 'hudson_s_bay', label: "Hudson's Bay" },
  { value: 'hunkemoller', label: 'Hunkemoller' },
  { value: 'ibs', label: 'IBS' },
  { value: 'iberia', label: 'Iberia' },
  { value: 'ifema', label: 'IFEMA' },
  { value: 'inno', label: 'Inno' },
  { value: 'intercorp', label: 'Intercorp' },
  { value: 'intermarche', label: 'Intermarche' },
  { value: 'invivo', label: 'Invivo' },
  { value: 'ishopchangi', label: 'iShopChangi' },
  { value: 'j_crew', label: 'J.Crew' },
  { value: 'janie_and_jack', label: 'Janie and Jack' },
  { value: 'jc_penney', label: 'JC Penney' },
  { value: 'jd_sports_go_outdoors', label: 'JD Sports - Go Outdoors' },
  { value: 'john_lewis', label: 'John Lewis' },
  { value: 'joules', label: 'Joules' },
  { value: 'jumbo', label: 'Jumbo' },
  { value: 'kabum_comercio_eletronico', label: 'Kabum Comercio Eletronico' },
  { value: 'kiabi', label: 'Kiabi' },
  { value: 'kleertjes', label: 'Kleertjes' },
  { value: 'koctas', label: 'Koctas' },
  { value: 'kogan', label: 'Kogan' },
  { value: 'kroger', label: 'Kroger' },
  { value: 'kruidvat', label: 'Kruidvat' },
  { value: 'kwik_fit', label: 'Kwik Fit' },
  { value: 'la_poste', label: 'La Poste' },
  { value: 'la_redoute', label: 'La Redoute' },
  { value: 'ldlc', label: 'LDLC' },
  { value: 'leen_bakker', label: 'Leen Bakker' },
  { value: 'leroy_merlin', label: 'Leroy Merlin' },
  { value: 'linio', label: 'Linio' },
  { value: 'liverpool', label: 'Liverpool' },
  { value: 'loblaws', label: 'Loblaws' },
  { value: 'l_oreal', label: "L'Oreal" },
  { value: 'macway', label: 'Macway' },
  { value: 'macy_s', label: "Macy's" },
  { value: 'madewell', label: 'Madewell' },
  { value: 'magasin_du_nord', label: 'Magasin du Nord' },
  { value: 'magazine_zum_globus', label: 'Magazine zum Globus' },
  { value: 'maisons_du_monde', label: 'Maisons du Monde' },
  { value: 'makro', label: 'Makro' },
  { value: 'mango', label: 'Mango' },
  { value: 'manomano', label: 'ManoMano' },
  { value: 'manor', label: 'Manor' },
  { value: 'manutan', label: 'Manutan' },
  { value: 'marisa', label: 'Marisa' },
  { value: 'marks_and_spencer', label: 'Marks & Spencer' },
  { value: 'materiel_chr_pro', label: 'Materiel CHR Pro' },
  { value: 'matelpro', label: 'Matelpro' },
  { value: 'mathis_home', label: 'Mathis Home' },
  { value: 'mathon', label: 'Mathon' },
  { value: 'maty', label: 'Maty' },
  { value: 'matalan', label: 'Matalan' },
  { value: 'maxeda', label: 'Maxeda' },
  { value: 'maykers', label: 'Maykers' },
  { value: 'mediamarkt_saturn', label: 'MediaMarkt Saturn' },
  { value: 'meubles_fr', label: 'Meubles.fr' },
  { value: 'miinto', label: 'Miinto' },
  { value: 'minted', label: 'Minted' },
  { value: 'misako', label: 'Misako' },
  { value: 'mm_mega_market', label: 'MM Mega Market' },
  { value: 'mobase_siemens', label: 'Mobase-Siemens' },
  { value: 'moda_operandi', label: 'Moda Operandi' },
  { value: 'modivo', label: 'Modivo' },
  { value: 'mondial_tissus', label: 'Mondial Tissus' },
  { value: 'monoprix', label: 'Monoprix' },
  { value: 'monshowroom', label: 'MonShowRoom' },
  { value: 'mountain_warehouse', label: 'Mountain Warehouse' },
  { value: 'mr_bricolage', label: 'Mr Bricolage' },
  { value: 'musgrave', label: 'Musgrave' },
  { value: 'myer', label: 'Myer' },
  { value: 'nature_and_decouvertes', label: 'Nature & Decouvertes' },
  { value: 'newegg', label: 'Newegg' },
  { value: 'nocibe', label: 'Nocibe' },
  { value: 'norauto', label: 'Norauto' },
  { value: 'nordstrom', label: 'Nordstrom' },
  { value: 'ntuc_fairprice', label: 'NTUC Fairprice' },
  { value: 'obelink', label: 'Obelink' },
  { value: 'ochsner_sport', label: 'Ochsner Sport' },
  { value: 'ocp_repartition', label: 'OCP Repartition' },
  { value: 'oechsle', label: 'Oechsle' },
  { value: 'office_depot', label: 'Office Depot' },
  { value: 'onceit', label: 'Onceit' },
  { value: 'onlinemetals_com', label: 'OnlineMetals.com' },
  { value: 'onbuy', label: 'OnBuy' },
  { value: 'oney', label: 'Oney' },
  { value: 'otto', label: 'Otto' },
  { value: 'palacio_de_hierro', label: 'Palacio de Hierro' },
  { value: 'pandacola', label: 'Pandacola' },
  { value: 'paris', label: 'Paris' },
  { value: 'partstown', label: 'PartsTown' },
  { value: 'pc_componentes', label: 'PC Componentes' },
  { value: 'perfume_s_club', label: "Perfume's Club" },
  { value: 'petcity', label: 'Petcity' },
  { value: 'pharmedistore', label: 'Pharmedistore' },
  { value: 'pharmaprov', label: 'Pharmaprov' },
  { value: 'phone_house', label: 'Phone House' },
  { value: 'pingo_doce', label: 'Pingo Doce' },
  { value: 'pixmania', label: 'Pixmania' },
  { value: 'place_des_tendances', label: 'Place des Tendances' },
  { value: 'praxis', label: 'Praxis' },
  { value: 'premier_farnell', label: 'Premier Farnell' },
  { value: 'printemps', label: 'Printemps' },
  { value: 'private_sport_shop', label: 'Private Sport Shop' },
  { value: 'privalia', label: 'Privalia' },
  { value: 'promart', label: 'Promart' },
  { value: 'promod', label: 'Promod' },
  { value: 'promofarma', label: 'PromoFarma' },
  { value: 'proudly_market', label: 'Proudly.Market' },
  { value: 'public_gr', label: 'Public.gr' },
  { value: 'pyramyd_air', label: 'Pyramyd Air' },
  { value: 'quirumed', label: 'Quirumed' },
  { value: 'rakuten', label: 'Rakuten' },
  { value: 'reedoo', label: 'Reedoo' },
  { value: 'renner', label: 'Renner' },
  { value: 'retif', label: 'Retif' },
  { value: 'rexel', label: 'Rexel' },
  { value: 'riachuelo', label: 'Riachuelo' },
  { value: 'ripley', label: 'Ripley' },
  { value: 'rs_components', label: 'RS Components' },
  { value: 'rubix', label: 'Rubix' },
  { value: 'rue_des_maquettes', label: 'Rue des Maquettes' },
  { value: 'rue_du_commerce', label: 'Rue du Commerce' },
  { value: 'rusta', label: 'Rusta' },
  { value: 'saks_com', label: 'Saks.com' },
  { value: 'saks_fifth_avenue', label: 'Saks Fifth Avenue' },
  { value: 'saloncentric', label: 'SalonCentric' },
  { value: 'sarenza', label: 'Sarenza' },
  { value: 'satair', label: 'Satair' },
  { value: 'saturn', label: 'Saturn' },
  { value: 'secret_sales', label: 'Secret Sales' },
  { value: 'sephora', label: 'Sephora' },
  { value: 'shop_apotheke', label: 'Shop Apotheke' },
  { value: 'shop_premium_outlets_shop_simon', label: 'Shop Premium Outlets - Shop Simon' },
  { value: 'showroomprive', label: 'Showroomprive' },
  { value: 'siam_makro', label: 'Siam Makro' },
  { value: 'siemens', label: 'Siemens' },
  { value: 'sligro', label: 'Sligro' },
  { value: 'snappy_gifts', label: 'Snappy Gifts' },
  { value: 'sncf', label: 'SNCF' },
  { value: 'sodimac', label: 'Sodimac' },
  { value: 'sonae', label: 'Sonae' },
  { value: 'sonepar', label: 'Sonepar' },
  { value: 'spartoo', label: 'Spartoo' },
  { value: 'sportzone', label: 'Sportzone' },
  { value: 'sprinter', label: 'Sprinter' },
  { value: 'stadium', label: 'Stadium' },
  { value: 'staples', label: 'Staples' },
  { value: 'suez', label: 'SUEZ' },
  { value: 'superdrug', label: 'Superdrug' },
  { value: 'superpharm', label: 'SuperPharm' },
  { value: 'sysco', label: 'Sysco' },
  { value: 'ta_ta_s_a', label: 'Ta-Ta S.A.' },
  { value: 'target_plus', label: 'Target Plus' },
  { value: 'teknosa', label: 'Teknosa' },
  { value: 'teract_invivo_retail', label: 'Teract - Invivo Retail' },
  { value: 'tesco', label: 'Tesco' },
  { value: 'thales', label: 'Thales' },
  { value: 'the_kase', label: 'The Kase' },
  { value: 'the_knot', label: 'The Knot' },
  { value: 'the_range', label: 'The Range' },
  { value: 'tiendamia', label: 'Tiendamia' },
  { value: 'tiendanimal', label: 'Tiendanimal' },
  { value: 'toolstation', label: 'Toolstation' },
  { value: 'totalplay', label: 'Totalplay' },
  { value: 'toyota_material_handling', label: 'Toyota Material Handling' },
  { value: 'tradeinn', label: 'TradeInn' },
  { value: 'trendy_foods', label: 'Trendy Foods' },
  { value: 'truffaut', label: 'Truffaut' },
  { value: 'twil', label: 'Twil' },
  { value: 'ubaldi', label: 'Ubaldi' },
  { value: 'united_farmers_of_alberta_ufa', label: 'United Farmers of Alberta - UFA' },
  { value: 'united_natural_foods_unfi', label: 'United Natural Foods (UNFI)' },
  { value: 'urban_outfitters', label: 'Urban Outfitters' },
  { value: 'vanden_borre', label: 'Vanden Borre' },
  { value: 'veepee', label: 'Veepee' },
  { value: 'venca', label: 'Venca' },
  { value: 'vente_unique', label: 'Vente-Unique' },
  { value: 'verdetierra', label: 'VerdeTierra' },
  { value: 'verishop', label: 'Verishop' },
  { value: 'vertbaudet', label: 'Vertbaudet' },
  { value: 'vidaxl', label: 'vidaXL' },
  { value: 'vink', label: 'Vink' },
  { value: 'virtual_expo', label: 'Virtual Expo' },
  { value: 'voelkner', label: 'voelkner' },
  { value: 'walmart', label: 'Walmart' },
  { value: 'watchfinder', label: 'WatchFinder' },
  { value: 'wayfair_professional', label: 'Wayfair Professional' },
  { value: 'wickes', label: 'Wickes' },
  { value: 'woolworths', label: 'Woolworths' },
  { value: 'worten', label: 'Worten' },
  { value: 'wurth_marketplace', label: 'Wurth Marketplace' },
  { value: 'xxxlutz', label: 'XXXLutz' },
  { value: 'yoox', label: 'Yoox' },
  { value: 'yves_rocher', label: 'Yves Rocher' },
  { value: 'zalando', label: 'Zalando' },
  { value: 'zap_group', label: 'Zap Group' },
  { value: 'zooplus', label: 'Zooplus' },
  { value: 'zoro', label: 'Zoro' },
  { value: 'zupply', label: 'Zupply' },
];

const MIRAKL_SUB_TYPE_LABEL_MAP = Object.fromEntries(
  MIRAKL_SUB_TYPE_CHOICES.map(({ value, label }) => [value, label])
);

const BADGE_COLORS = ['blue', 'green', 'red', 'yellow', 'orange', 'indigo', 'purple', 'pink', 'gray'] as const;

const MIRAKL_SUB_TYPE_COLOR_OVERRIDES: Record<string, typeof BADGE_COLORS[number]> = {
  mirakl: 'indigo',
  abb: 'red',
  acer: 'green',
  asos: 'gray',
  auchan: 'red',
  best_buy: 'yellow',
  bol_com: 'blue',
  boulanger: 'orange',
  carrefour: 'blue',
  castorama: 'blue',
  cdiscount: 'orange',
  decathlon: 'blue',
  fnac_darty: 'orange',
  home_depot: 'orange',
  leroy_merlin: 'green',
  manomano: 'orange',
  mediamarkt_saturn: 'red',
  monoprix: 'red',
  otto: 'red',
  rakuten: 'red',
  sephora: 'pink',
  target_plus: 'red',
  walmart: 'blue',
  zalando: 'gray'
};

const getMiraklSubtypeFallbackColor = (value: string) => {
  const hash = value.split('').reduce((total, char) => total + char.charCodeAt(0), 0);
  return BADGE_COLORS[hash % BADGE_COLORS.length];
};

export const isKnownMiraklSubType = (value?: string | null) =>
  Boolean(value && value in MIRAKL_SUB_TYPE_LABEL_MAP);

export const getMiraklSubType = (type?: string | null) => {
  if (isKnownMiraklSubType(type)) {
    return type as string;
  }
  return null;
};

export const getMiraklSubtypeLabel = (type?: string | null) => {
  const resolvedSubtype = getMiraklSubType(type);
  if (!resolvedSubtype) {
    return null;
  }
  return MIRAKL_SUB_TYPE_LABEL_MAP[resolvedSubtype] || MIRAKL_SUB_TYPE_LABEL_MAP[DEFAULT_MIRAKL_SUB_TYPE];
};

export const getMiraklSubtypeBadge = (type?: string | null) => {
  const resolvedSubtype = getMiraklSubType(type);
  if (!resolvedSubtype) {
    return null;
  }
  return {
    text: getMiraklSubtypeLabel(type) || 'Mirakl',
    color: MIRAKL_SUB_TYPE_COLOR_OVERRIDES[resolvedSubtype] || getMiraklSubtypeFallbackColor(resolvedSubtype),
    hoverText: 'Mirakl'
  };
};
