image: atlassian/default-image:4

pipelines:
  branches:
    dev:
      - step:
          name: "Build"
          script:
            - export VITE_APP_API_GRAPHQL_URL=$DEV_API_GRAPHQL_URL
            - export VITE_APP_SENTRY_DSN=$SENTRY_DSN
            - export VITE_APP_SENTRY_ENV=development
            - npm install -g npm
            - npm install
            - npm run build
            - cd dist && zip -r ../dist.zip .
          artifacts:
            - dist.zip
      - step:
          name: "Deploy"
          deployment: "Staging"
          script:
            - pipe: atlassian/scp-deploy:1.3.0
              variables:
                USER: $SSH_USER
                SERVER: $SSH_HOST
                REMOTE_PATH: '/home/onesilla'
                LOCAL_PATH: 'dist.zip'
            - cat ./scripts/deploy.sh | ssh $SSH_USER@$SSH_HOST
    master:
      - step:
          name: "Build"
          script:
            - export VITE_APP_API_GRAPHQL_URL=$PROD_API_GRAPHQL_URL
            - export VITE_APP_SENTRY_DSN=$SENTRY_DSN
            - export VITE_APP_SENTRY_ENV=production
            - npm install -g npm
            - npm install
            - npm run build
            - cd dist && zip -r ../dist.zip .
          artifacts:
            - dist.zip
      - step:
          name: "Deploy"
          deployment: "Production"
          script:
            - pipe: atlassian/scp-deploy:1.3.0
              variables:
                USER: $SSH_USER
                SERVER: $SSH_HOST
                REMOTE_PATH: '/home/onesilla'
                LOCAL_PATH: 'dist.zip'
            - cat ./scripts/deploy.sh | ssh $SSH_USER@$SSH_HOST
